version: '3.8'

services:
  tunnelfy:
    build: .
    container_name: tunnelfy_app
    restart: unless-stopped
    ports:
      - "2222:2222"
      - "8000:8000"
    volumes:
      - ./.env:/root/.env
    # environment:
    #   - LOG_REQUESTS=true
